// WotBlitzNewYearAuction.Angular/WotBlitzNewYearAuction/src/app/Auction/Components/auction/auction.component.ts
import { Component, Signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { AuctionApiService } from '../../Services/auction-api.service';
import { AsyncPipe, DecimalPipe, NgForOf, NgIf } from '@angular/common';
import { toSignal } from '@angular/core/rxjs-interop';
import { AuctionItem } from '../../../Model/AuctionItem';
import { TankCardComponent } from '../tank-card/tank-card.component';
import { MatCardModule } from '@angular/material/card';
import { VehicleSortPipe } from '../../Pipes/vehicle-sort.pipe';
import { MatTableModule } from '@angular/material/table';
import { PREMIUM_COLOR } from '../../constants';

@Component({
  selector: 'app-auction',
  standalone: true,
  imports: [
    MatButtonModule,
    NgIf,
    NgForOf,
    AsyncPipe,
    TankCardComponent,
    MatCardModule,
    VehicleSortPipe,
    MatTableModule,
    DecimalPipe,
  ],
  templateUrl: './auction.component.html',
  styleUrl: './auction.component.css',
})
export class AuctionComponent {
  public auctionItems: Signal<AuctionItem[] | undefined> = toSignal(
    this.auctionApi.getAuctionItems(),
    { initialValue: undefined },
  );
  constructor(private auctionApi: AuctionApiService) {}

  protected readonly PREMIUM_COLOR = PREMIUM_COLOR;

  public priceDrop(currentPrice?: number, initialPrice?: number): string | undefined {
    if (currentPrice === initialPrice || currentPrice === undefined || initialPrice === undefined) {
      return undefined;
    }
    const diff = initialPrice - currentPrice;
    const diffPercent = Math.round(100 * (diff / initialPrice));
    return ` -${diff} (${diffPercent}%)`;
  }

  public availablePercent(current: number, total: number): number {
    return Math.round(100 * (current / total));
  }

  public availableColor(current: number, total: number): string {
    const percent = this.availablePercent(current, total);
    return percent < 10 ? 'red' : 'green';
  }
}

<h4>
  <a mat-button href="https://eu.wotblitz.com/en/auction/#/">WOT Blitz Auction</a>
</h4>

<mat-progress-spinner *ngIf="isLoading()"
  class="example-margin"
  color="accent"
  mode="indeterminate">
</mat-progress-spinner>

<div style="margin: 5px;">Next price drop in {{timeToNextDrop()}}</div>
<div class="auto-center">
<mat-progress-bar
  style="width: 90%"
  color="accent"
  mode="determinate"
  [value]="timeUntilRequestInPercent()"
  >
</mat-progress-bar>
</div>

<div *ngIf="auctionItems$ | async as auctionItems" class="auction-items-list">
  <mat-card *ngFor="let auctionItem of auctionItems">
    <mat-card-content class="card-content">
      <app-tank-card [vehicle]="auctionItem.entity"></app-tank-card>
      <span [style]="auctionItem.entity?.is_premium | vehicleSort: auctionItem.entity?.is_collectible"> {{auctionItem.entity?.user_string}} </span>
      <table class="mat-elevation-z8 auction-item-info-table">
        <tbody>
          <tr>
            <td style="text-align:left;">Current Price</td>
            <td style="text-align:right;">
              <span [style.color]="PREMIUM_COLOR">{{auctionItem.price?.value | number}}</span>
              {{priceDrop(auctionItem.price?.value, auctionItem.initialPrice)}}
            </td>
          </tr>
          <tr>
            <td style="text-align:left;">Available</td>
            <td style="text-align:right;">
              <span [style.color]="availableColor(auctionItem.current_count, auctionItem.initial_count)">
                {{auctionItem.current_count | number}}
              </span>
              / {{auctionItem.initial_count | number}}
              ({{availablePercent(auctionItem.current_count, auctionItem.initial_count)}}%)
            </td>
          </tr>
          <tr>
            <td style="text-align:left;">Available until</td>
            <td style="text-align:right;">
              {{auctionItem.available_before | date:'shortDate' }}
            </td>
          </tr>
          <tr>
            <td style="text-align:left;">Next price</td>
            <td style="text-align:right;">
              <span [style.color]="PREMIUM_COLOR">
                {{auctionItem.next_price?.value | number}}
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </mat-card-content>
  </mat-card>
</div>

// WotBlitzNewYearAuction.React/frontend/src/Components/Auction.tsx
// @flow
import * as React from 'react';
import { UpdateAuctionPeriod, useAuction } from './UseAuction';
import {
  Alert,
  Box,
  Card,
  CardContent,
  CircularProgress,
  LinearProgress,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Typography,
} from '@mui/material';
import { AuctionItem } from '../Model/AuctionItem';
import { CollectibleColor, PremiumColor, TankCard } from './TankCard';

export function Auction() {
  const { loading, auctionItems, error, timeToNextDrop, timeUntilRequestInSec } = useAuction();

  const timeUntilNextRequestPercent = Math.round(
    (100 * 1000 * timeUntilRequestInSec) / UpdateAuctionPeriod,
  );

  const sortByAvailableDate = (a: AuctionItem, b: AuctionItem): number => {
    if (a.available_before === b.available_before) {
      return 0;
    }
    return a.available_before > b.available_before ? 1 : -1;
  };

  const nameColor = (isPremium: boolean, isCollectible: boolean): string => {
    if (!isPremium && !isCollectible) {
      return 'text.secondary';
    }
    return isCollectible ? CollectibleColor : PremiumColor;
  };

  const priceDrop = (currentPrice?: number, initialPrice?: number): string | undefined => {
    if (currentPrice === initialPrice || currentPrice === undefined || initialPrice === undefined) {
      return undefined;
    }
    const diff = initialPrice - currentPrice;
    const diffPercent = Math.round(100 * (diff / initialPrice));
    return ` -${diff} (${diffPercent}%)`;
  };

  const availablePercent = (current: number, total: number): number => {
    return Math.round(100 * (current / total));
  };

  const availableColor = (current: number, total: number): string => {
    const percent = availablePercent(current, total);
    return percent < 10 ? 'red' : 'green';
  };

  if (error) {
    return <Alert severity="error">{error}</Alert>;
  } else if (loading) {
    return <CircularProgress />;
  } else {
    return (
      <>
        <Box>Next price drop in {timeToNextDrop}</Box>
        <LinearProgress
          variant="determinate"
          value={timeUntilNextRequestPercent}
          sx={{ margin: '1em' }}
        />
        <Box display="flex" flexDirection="row" flexWrap="wrap" gap="5px">
          {auctionItems
            .filter((i) => i.available && i.current_count > 0)
            .sort(sortByAvailableDate)
            .map((auctionItem) => {
              return (
                <Card
                  sx={{ maxWidth: '20rem', width: '20rem' }}
                  key={`card-${auctionItem.entity!.id}`}
                >
                  <CardContent>
                    <Box
                      display="flex"
                      flexDirection="column"
                      alignItems="center"
                      justifyContent="center"
                    >
                      <TankCard
                        key={`tank-card-${auctionItem.entity!.id}`}
                        vehicle={auctionItem.entity}
                      ></TankCard>
                      <Typography
                        variant="h6"
                        component="div"
                        color={nameColor(
                          auctionItem.entity!.is_premium,
                          auctionItem.entity!.is_collectible,
                        )}
                      >
                        {auctionItem.entity!.user_string}
                      </Typography>
                    </Box>
                    <TableContainer component={Paper} sx={{ width: '100%' }}>
                      <Table sx={{ width: '100%' }} size="small" aria-label="a dense table">
                        <TableBody>
                          <TableRow>
                            <TableCell component="th" scope="row">
                              Current Price
                            </TableCell>
                            <TableCell align="right">
                              <span style={{ color: PremiumColor }}>
                                {auctionItem.price?.value}
                              </span>
                              {priceDrop(auctionItem.price?.value, auctionItem.initialPrice)}
                            </TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell component="th" scope="row">
                              Available
                            </TableCell>
                            <TableCell align="right">
                              <span
                                style={{
                                  color: availableColor(
                                    auctionItem.current_count,
                                    auctionItem.initial_count,
                                  ),
                                }}
                              >
                                {auctionItem.current_count}
                              </span>
                              / {auctionItem.initial_count} (
                              {availablePercent(
                                auctionItem.current_count,
                                auctionItem.initial_count,
                              )}
                              )%)
                            </TableCell>
                          </TableRow>
                          <TableRow>
                            <TableCell component="th" scope="row">
                              Available until
                            </TableCell>
                            <TableCell align="right">
                              {new Date(auctionItem.available_before).toLocaleDateString('de-DE')}
                            </TableCell>
                          </TableRow>
                          <TableRow sx={{ border: 0 }}>
                            <TableCell component="th" scope="row" sx={{ border: 0 }}>
                              Next price
                            </TableCell>
                            <TableCell align="right" sx={{ border: 0 }}>
                              <span style={{ color: PremiumColor }}>
                                {auctionItem.next_price?.value}
                              </span>
                            </TableCell>
                          </TableRow>
                        </TableBody>
                      </Table>
                    </TableContainer>
                  </CardContent>
                </Card>
              );
            })}
        </Box>
      </>
    );
  }
}
