// WotBlitzNewYearAuction.React/frontend/src/Components/TankCard.tsx
// @flow
import * as React from 'react';
import { Vehicle } from '../Model/Vehicle';
import './TankCard.css';
import { nationAsset, tankTypeAsset } from '../helpers';

export const PremiumColor = '#d4d481';
export const CollectibleColor = '#64c8f5';

type Props = {
  vehicle?: Vehicle;
};

export function TankCard({ vehicle }: Props) {
  const tankTier = (tier: string, isPremium: boolean, isCollectible: boolean) => {
    if (isPremium) {
      if (isCollectible) {
        return <b style={{ color: CollectibleColor, fontSize: '16px' }}>{tier}</b>;
      } else {
        return <b style={{ color: PremiumColor, fontSize: '16px' }}>{tier}</b>;
      }
    } else {
      return <b style={{ fontSize: '16px' }}>{tier}</b>;
    }
  };

  if (!vehicle) {
    return <></>;
  }
  return (
    <div className="tank-image">
      <div
        className="tank-flag-background"
        style={{ backgroundImage: `url(${nationAsset(vehicle.nation)}` }}
      ></div>
      <div className="tank-tier">
        {tankTier(vehicle.roman_level, vehicle.is_premium, vehicle.is_collectible)}
      </div>
      <img className="tank-preview" src={vehicle.preview_image_url} alt={vehicle.user_string} />
      <img
        className="tank-type"
        src={tankTypeAsset(vehicle.type_slug, vehicle.is_premium, vehicle.is_collectible)}
        alt={vehicle.type_slug}
      />
    </div>
  );
}

// WotBlitzNewYearAuction.Angular/WotBlitzNewYearAuction/src/app/Auction/Components/tank-card/tank-card.component.ts
import { Component, Input } from '@angular/core';
import { Vehicle } from '../../../Model/Vehicle';
import { NationBackgroundPipe } from '../../Pipes/nation-background.pipe';
import { VehicleSortPipe } from '../../Pipes/vehicle-sort.pipe';
import { NgOptimizedImage } from '@angular/common';
import { VehicleTypePipe } from '../../Pipes/vehicle-type.pipe';

@Component({
  selector: 'app-tank-card',
  standalone: true,
  imports: [NationBackgroundPipe, VehicleSortPipe, NgOptimizedImage, VehicleTypePipe],
  templateUrl: './tank-card.component.html',
  styleUrl: './tank-card.component.css',
})
export class TankCardComponent {
  @Input() vehicle?: Vehicle;
}

<div class="tank-image">
  <div class="tank-flag-background" [style]="vehicle?.nation | nationBackground"></div>
  <div class="tank-tier">
    <b [style]="vehicle?.is_premium | vehicleSort: vehicle?.is_collectible">{{vehicle?.roman_level}}</b>
  </div>
  <img [src]="vehicle?.preview_image_url" class="tank-preview" [alt]="vehicle?.user_string" />
  <img [src]="vehicle?.type_slug | vehicleType:vehicle?.is_premium:vehicle?.is_collectible" class="tank-type" [alt]="vehicle?.type_slug" />
</div>
